services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"

  api:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  parser:
    build:
      context: .
      dockerfile: parser.Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres
      - api

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  celery:
    build:
      context: .
      dockerfile: parser.Dockerfile
    command: ['python', '-m', 'celery', '-A', 'celery_config.celery_app', 'worker']
    depends_on:
      - redis
      - postgres
      - parser
    env_file:
      - .env

volumes:
  postgres:
  redis:
